### post blog 1
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5paGFvOTkiLCJpZCI6IjY3MjAyYzk2NTVmOGIyOGE4NmRiZWYyYSIsImlhdCI6MTczMDIyNjk0OX0.b-6nVymD55o0uTUuf7gDlacsvl7hbsu2NS6wIUspaxI

{
  "title": "TTTitle 1",
  "author": "AAAuthor 1",
  "url": "UURRLL 1",
  "likes": 111
}

### post blog 2
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "TTTitle 2",
  "author": "AAAuthor 2",
  "url": "UURRLL 2",
  "likes": 222
}

### post wrongly
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "AAAuthor 3",
  "url": "UURRLL 3",
  "likes": 333
}

### get all blogs
GET http://localhost:3001/api/blogs

### get wrongly
GET http://localhost:3001/api